config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users, only: [:show] do 
    resources :items, only: [:create, :destroy]
  end

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end 

  root to: 'welcome#index'
  
  get 'welcome/index'

  get 'welcome/about'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  
  validates :name, length: {minimum: 5}, presence: true
  default_scope {order "created_at DESC"}
  
  def days_left
    7-(DateTime.now.to_date - created_at.to_date).to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
 
  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # def after_sign_in_path_for(user)
  #   user_path(user)
  # end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
  
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.visible_to(current_user)
  end
  #initialize task as instance variable
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user), notice: "\"#{@item.name}\" was added successfully." }
        format.js
      end    
    else 
      flash[:error] = "Error adding item. Please try again."
      redirect_to user_path(current_user)
    end  
  end
    
  def destroy
    @item = Item.find(params[:id])
    name = @item.name
      if @item.destroy
        flash[:notice] = "\"#{name}\" was deleted successfully."
      else
        flash[:error] = "There was an error deleting the item. Please try again."
      end

    respond_to do |format|
      format.html { redirect_to user_path(current_user) }
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end

end

app/controllers/registrations_controller.rb
# class RegistrationsController < Devise::RegistrationsController
#   protected

#   def after_inactive_sign_up_path_for(resource)
#     "users#show"
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id] || current_user.id)
    @items = @user.items
  end

  def update
    
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def format_days_remaining(days_left)
    if days_left >= 6
      "active"
    elsif days_left >= 4 
      "pending"
    else 
      "urgent"
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="container">

  <% if current_user %>
    <%= form_for [current_user, Item.new], remote: true do |f| %>
      <div class="form-group col-md-8">
        <%= f.label :description, class: "col-md-2" %>
        <%= f.text_field :name, autofocus: true, placeholder: "Enter item", class: "js-item-name col-md-6" %>
      </div>
      <div class="form-group col-md-6">
        <%= f.submit "Add Item To List", class: 'btn btn-success col-md-4' %>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/items/_item.html.erb
<%= content_tag :li, class: 'list-group-item todo-item-even todo-item-odd', id: "item-#{item.id}" do %>

  <%= item.name %>
  <%= link_to " ", [current_user, item],  method: :delete, class: 'glyphicon glyphicon-ok pull-right', remote: true %>
  <div class="text-center-small">
    <small class="<%= format_days_remaining(item.days_left) %>">
      <%= item.days_left.to_s. + " days left to complete"  %>
    </small>
  </div>
<% end %>

app/views/items/create.js.erb
<% if @item.valid? %>
  $('.js-items').prepend("<%= escape_javascript(render(@item)) %>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form') %>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form') %>");
<% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).fadeOut("slow");
  $('.alert').html("<button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %>");
  $('.alert').addClass('alert-warning');
  $('.alert').removeClass('remove');
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      
      <div class="user-info pull-right">
        <% if user_signed_in? %>
          <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
          Signed in as: <strong> <%= link_to current_user.email, user_path(current_user) %> </strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>
    <div class="flash">
      <% if flash.now[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% end %>
    </div>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<div class="container-fluid">
  <h3 class="text-center">Hello <%= @user.email %></h3>
  <div class="row">
    <div class="col-md-lg">
      <h3 class="text-center">Your To Do's</h3>
      <div class="new-item">
        <%= render "items/form" %>
      </div>
      
      <ul class = "list-group js-items" >
        <%= render @items %>
      </ul>

  </div>
</div>

app/views/welcome/about.html.erb
 <h1>About Blocitoff</h1>
 <p>Created by: Me</p>

app/views/welcome/index.html.erb
 <h1>Welcome to Blocitoff</h1>
 <p id="index-title">This is the home page for Blocitoff.</p>